ALTER TABLE shifts
  ADD COLUMN IF NOT EXISTS expected_balance INTEGER,
  ADD COLUMN IF NOT EXISTS difference INTEGER,
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS approved_by UUID,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
